A cláusula catch tem que ser capaz de tratar todas as possíveis exceptions que são lançadas.
Exemplo:
Erro de compilação: Uma classe dentro do bloco try daz throw de RuntimeException, porém o catch trata apenas IOEXception.

--------------

Só precisa por throws quando o método lança uma exception verificada (Exception), quando é uma RuntimeException não precisa mas pode.

--------------

Quando é feito um try catch, caso exista um catch que nunca será utilizado (porque já tem um catch mais genérico), o código
não compilará:
Ex: Unreachable catch block for IOException. It is already handled by the catch block for Exception

--------------

RuntimeException: Não-verificadas, não precisam ser tratadas com try /catch, ou serem passadas adiante com throws (apenas na origem precisa ser lançada com throws).
Exception: Verificadas, precisam ser tratadas com try /catch, ou serem passadas adiante com throws.

-------------

Caso exista um catch mais genérico abaixo de um catch específico, este catch genérico não será alcançado.
    try {
        throw new FileNotFoundException();
    } catch (IOException e) {
        System.out.println("FileNotFoundException");
    } catch (Exception e) { // Line 2
        System.out.println("Test");
    }

-------------

Um parâmetro de uma exception não pode ser atribuido, exemplo:

} catch (RuntimeException | IOException e) { // Line 1
    e = new RuntimeException(e); // Line 2
}

-------------

O Try requer sempre um finally, não necessariamente um catch
try {
    
} finally {
    
}

-------------

Ao dar print numa exception, o formto esperado é: classe + mensagem:

com.java17.certification.overview.tests.MyException: A custom test

considerando:

package com.java17.certification.overview.tests;

class MyException extends RuntimeException {
	
	MyException(String message) {
		super(message);
	}
	
}
-------------